use_frameworks!

platform :ios, '8.0'

target 'TGVA_Example' do
  pod 'TGVA', :path => '../'

  target 'TGVA_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
